---
services:

  postgres:
    image: postgres:15.1-alpine
    hostname: postgres
    ports:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: alerts
